#!/usr/bin/env bash
set -Eeuo pipefail
USER_CONFIG_DIR="${XDG_CONFIG_HOME}/cargo-nextest"
USER_CONFIG_FILE="${USER_CONFIG_DIR}/config.toml"

print_help=0
if [[ $# -eq 0 ]]; then
  print_help=1
fi
for arg in "$@"; do
  case "${arg}" in
  --help | -h)
    print_help=1
    ;;
  esac
done

if [[ ${print_help} -eq 1 ]]; then
  # Prepend a notice in the help info
  echo "(Note this is cargo-nextest-xdg, a shim for cargo-nextest)" >&2
  command cargo-nextest "$@"
  exit $?
fi

if ! workspace_root="$(dirname "$(cargo locate-project --workspace | jq --raw-output '.root')")"; then
  exit 1
fi

workspace_config="${workspace_root}/.config/nextest.toml"
rule="${workspace_config}:${USER_CONFIG_FILE}:file"

if [[ ! -f ${workspace_config} ]]; then
  # No repo-level config file

  if [[ -f ${USER_CONFIG_FILE} ]]; then
    # User-level config file exists, need to boxx up nextest
    exec boxxy --log-level warn --no-config --rule "${rule}" cargo nextest "$@"
  fi
fi

# Criteria not met; Do not override existing nextest config
command cargo-nextest "$@"
exit $?
